# Generated by Django 4.2.30 on 2026-06-09 21:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "Actor_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("FirstName", models.CharField(blank=True, max_length=200, null=True)),
                ("LastName", models.CharField(blank=True, max_length=200, null=True)),
                ("Biography", models.TextField(blank=True)),
                (
                    "Picture",
                    models.ImageField(blank=True, null=True, upload_to="Actoravatars/"),
                ),
                ("Birth_date", models.DateField(blank=True, null=True)),
                (
                    "Gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "Director_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("FirstName", models.CharField(blank=True, max_length=200, null=True)),
                ("LastName", models.CharField(blank=True, max_length=200, null=True)),
                ("Biography", models.TextField(blank=True, null=True)),
                ("Picture", models.BinaryField(blank=True, null=True)),
                ("Birth_date", models.DateField(blank=True, null=True)),
                (
                    "Gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("excerpt", models.TextField(blank=True)),
                ("content", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="journals/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "Movie_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("Title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "Genre",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Ac", "Action"),
                            ("Ad", "Adventure"),
                            ("An", "Animation"),
                            ("Co", "Comedy"),
                            ("Cr", "Crime"),
                            ("Do", "Documentary"),
                            ("Dr", "Drama"),
                            ("Fa", "Fantasy"),
                            ("Hi", "Historical / Biopic"),
                            ("Ho", "Horror"),
                            ("Mu", "Musical"),
                            ("My", "Mystery"),
                            ("Ro", "Romance"),
                            ("Sc", "Science Fiction (Sci-Fi)"),
                            ("Th", "Thriller"),
                            ("Wa", "War"),
                        ],
                        max_length=2,
                    ),
                ),
                ("Description", models.TextField(blank=True)),
                (
                    "IMDBscore",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "Poster",
                    models.ImageField(blank=True, null=True, upload_to="Movieavatars/"),
                ),
                (
                    "Trailer",
                    models.FileField(blank=True, null=True, upload_to="trailers/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MovieActor",
            fields=[
                (
                    "MovieActor_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("Description", models.TextField(blank=True, default="Unknown")),
                ("role", models.CharField(default="Unknown", max_length=100)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Actors",
                        to="Movie.actor",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Movies",
                        to="Movie.movie",
                    ),
                ),
            ],
            options={
                "unique_together": {("movie", "actor")},
            },
        ),
        migrations.AddField(
            model_name="movie",
            name="MovieActor",
            field=models.ManyToManyField(through="Movie.MovieActor", to="Movie.actor"),
        ),
        migrations.AddField(
            model_name="movie",
            name="MovieDirector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Movies",
                to="Movie.director",
            ),
        ),
    ]
