# Generated by Django 4.2.30 on 2026-06-09 21:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Users", "0001_initial"),
        ("Movie", "0001_initial"),
        ("Recommendations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInformationFormovieSuggestions",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="userinformation",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "aveIMDBSc",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "interestInAction",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "interestInComedy",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "interestInDrama",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "interestInViolent",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "interestInFamilyFriendly",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "favActor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="favactor",
                        to="Movie.actor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="moviewatched",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userinform",
                to="Movie.movie",
            ),
        ),
        migrations.AddField(
            model_name="moviewatched",
            name="userInform",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userinform",
                to="Recommendations.userinformationformoviesuggestions",
            ),
        ),
        migrations.AddConstraint(
            model_name="moviewatched",
            constraint=models.UniqueConstraint(
                fields=("userInform", "movie"), name="unique_movie_watched"
            ),
        ),
    ]
